name: novaverse
description: "NovaVerse - A lightweight mobile streaming app like OBS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: >=3.4.0 <4.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_colorpicker: ^1.1.0
  video_player: ^2.9.1
  path_provider: ^2.1.4
  uuid: ^4.5.1
  audioplayers: ^6.1.0
  wakelock_plus: ^1.2.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
